### ISSUE TITLE
Localization: ID

### ISSUE THREAD

**Issue by adm-smiotaku** [smiotaku/saeskin#2]
Selamat datang kembali [Sukabumi Otaku Network](https://web.facebook.com/smiotaku?__cft__[0]=AZUdHyvaW7pft_2JkItVR-VdVwLnOpTL3NDkCAfWko6A0FvIYykdTaXLmqAJNN7acWXVqRVyDtpmvhogk6MqGApoVN4ZKM_I6PFGliHdw8Mu8fnrHMnTzhoRj__LUKgCU0w0oJCC6iPVfklAxgPYe_uA7XakbmhIpxyWoTzUgIX43tm84sC2MUsL96gOK2TVo6c&__tn__=-]K-R), mungkin aku ada poin soal lokalisasi yang anda buat, ada beberapa terjemahan yang seharusnya tidak perlu anda terjemahkan.. seperti Ekualiser anda terjemahkan Pengatur Suara, sebaiknya anda keep ekualiser aja
lalu ada beberapa bagian yang belum anda terjemahkan, mungkin saya bisa bantu beberapa, seperti
- Tray Control  > Kontrol Tray
- yang "daftar putar anda", ganti ke "daftar putarmu" (biar lebih simpel)

Sekian dari saya, Terima kasih

[Lieba Natur Brilian](https://web.facebook.com/naturbrilian28?__cft__[0]=AZUdHyvaW7pft_2JkItVR-VdVwLnOpTL3NDkCAfWko6A0FvIYykdTaXLmqAJNN7acWXVqRVyDtpmvhogk6MqGApoVN4ZKM_I6PFGliHdw8Mu8fnrHMnTzhoRj__LUKgCU0w0oJCC6iPVfklAxgPYe_uA7XakbmhIpxyWoTzUgIX43tm84sC2MUsL96gOK2TVo6c&__tn__=-UC%2CP-R)

**Comment by naturbrilian** [comment]
halo, ini tambahan dari post saya yang di Facebook tadi, seperti

1. Pilih mode mu > Pilih mode kamu
2. Pilih Desain mu > Pilih Desain kamu (context on skin settings page for Home, Tray control and Now Playing design)
3. keep "kulit" to "skin"
4. Playlist & Library > Playlist & Pustaka

Sisanya, untuk terjemahan ke Bahasa Indonesia sudah oke~

**Comment by naturbrilian** [comment]
[Revisi terjemahan Bahasa Indonesia SaeSkin.txt](https://github.com/smiotaku/saeskin/files/12437777/Revisi.terjemahan.Bahasa.Indonesia.SaeSkin.txt)

Update, ada yang aku tambahin lagi, jadi saya taruh di notepad aja, tambahan revisi terjemahan dari Tachi-rai
Mungkin segitu dulu, string terjemahan mungkin dapat berubah sewaktu-waktu kalau ada penambahan fitur dari itu skin sendiri

**Comment by adm-smiotaku** [comment]
Catatan:  
- Bukan **After the character placement** tapi **Alter the character placement**
- [**Ekualiser** tidak akan digunakan karena bukan bahasa indonesia](https://www.kbbi.web.id/ekualiser), menggunakan **Equalizer** saja
- [selaras lebih ke nada / suara](https://www.kbbi.web.id/laras) jadi sepertinya tidak cocok digunakan selain untuk nada / suara, lebih memilih "Sesuaikan"

**Comment by adm-smiotaku** [comment]
> [Revisi terjemahan Bahasa Indonesia SaeSkin.txt](https://github.com/smiotaku/saeskin/files/12437777/Revisi.terjemahan.Bahasa.Indonesia.SaeSkin.txt)
> 
> Update, ada yang aku tambahin lagi, jadi saya taruh di notepad aja, tambahan revisi terjemahan dari Tachi-rai Mungkin segitu dulu, string terjemahan mungkin dapat berubah sewaktu-waktu kalau ada penambahan fitur dari itu skin sendiri

Rev:


- Bukan After the character placement tapi Alter the character placement
- [Ekualiser tidak akan digunakan karena bukan bahasa indonesia](https://www.kbbi.web.id/ekualiser), menggunakan Equalizer saja
- [selaras lebih ke nada / suara](https://www.kbbi.web.id/laras) jadi sepertinya tidak cocok digunakan selain untuk nada / suara, lebih memilih "Sesuaikan"

**Comment by naturbrilian** [comment]
lebih baik keep aja untuk equalizer ini

kalau ke "sesuaikan" itu masuk akal

oh waif alter ya, okedeh

karena ini aku tulis manual semua di Notepad, jadi agak gak keliatan

**Comment by adm-smiotaku** [comment]
> lebih baik keep aja untuk equalizer ini
> 
> kalau ke "sesuaikan" itu masuk akal
> 
> oh wait alter ya, okedeh
> 
> karena ini aku tulis manual semua di Notepad, jadi agak gak keliatan

sudah kami sediakan di repo https://github.com/smiotaku/saeskin/tree/main/src/lang tinggal fork dan edit saja

**Comment by naturbrilian** [comment]
Okay, thank you i will check it~

> > lebih baik keep aja untuk equalizer ini
> > kalau ke "sesuaikan" itu masuk akal
> > oh wait alter ya, okedeh
> > karena ini aku tulis manual semua di Notepad, jadi agak gak keliatan
> 
> sudah kami sediakan di repo https://github.com/smiotaku/saeskin/tree/main/src/lang tinggal fork dan edit saja
