### ISSUE TITLE
Penambahan dukungan stop melalui long press di tombol play & dukungan teks berjalan ketika kursor mouse diarahkan

### ISSUE THREAD

**Issue by naturbrilian** [smiotaku/saeskin#20]
Halo, mengingat tampilan pemutar ini tidak mendukung tindakan seperti 
1. stop atau karena emang tidak tersedia.. jadi saya ingin rikues agar untuk ditambahkan dukungan stop melalui long-press di tombol play, mengingat kebiasaan setelah menyetel lagu langsung saya stop (karena selama ini saya menggunakan tombol hotkeys untuk stop)
2. lalu kedua mengingat ada beberapa metadata lagu yang judulnya sangat panjang, semisal ini dibuat berjalan tulisannya bisa? saat kursor/mouse diarahkan (referensi spotify, ketika kursor diarahkan judul akan berjalan)
![Cuplikan layar 2023-09-03 160012](https://github.com/smiotaku/saeskin/assets/9246423/dba36d14-e9ef-4750-bce4-54af9dcd20a8)

Terima kasih, sebelumnya

**Comment by adm-smiotaku** [comment]
Added https://github.com/smiotaku/saeskin-zzz/blob/development/releases/changelog.md#200923
